Feat/eng 268 navbar redesign
Polkamarkets/polkamarkets-web pull request #426
Opened 2024-02-28 14:58 UTC by danielgek

## 🗃 Story Description

_Link to Shortcut card, if PR is part of a story._

## 🧪 Test Suite
- Navbar Actions
  - [ ] Switch between light and dark mode across pages
  - [ ] Network Switcher
  - [ ] Wrong Network Modal
- Homepage Markets Navigation
  - [ ] Filters
  - [ ] Sorting
  - [ ] Search
- Pages Content
  - [ ] Homepage
  - [ ] Create Market Page
  - [ ] Market Page
  - [ ] Portfolio
- Trading (**Optional** - only if PR involves related components or `polkamarkets-js`)
  - [ ] Slider + MAX button
  - [ ] Buy Outcome Shares
  - [ ] Sell Outcome Shares
  - [ ] Add Liquidity 
  - [ ] Remove Liquidity
 
  ## 📝 Footnotes
  _Noting to add._

2024-02-29 17:16 UTC, danielgek commented
This PR also 

Closes ENG-274 
Closes ENG-275

2024-03-12 16:15 UTC, rsmarques requested changes
Looking good @danielgek! 

A few notes:

- Check my `username || Unnamed` comment above
- Dropdown colors aren't showing up properly on my side (probably due to my white mode system config)

<img width="263" alt="image" src="https://github.com/Polkamarkets/polkamarkets-web/assets/4268735/6320c8cd-e667-4b83-8c6b-f58cae521c04">

2024-03-12 16:15 UTC, rsmarques commented on src/components/Header/ProfileMenu/ProfileMenu.tsx
> +                    <span className={styles.menuUserName}>Unamed</span>
Typo: `Unnamed`

Shouldn't it be `{username || 'Unnamed'}` @danielgek? It's already computed above

2024-03-14 11:08 UTC, danielgek commented
@rsmarques fixed both issues and rebased

2024-03-15 11:20 UTC, rsmarques approved these changes
@danielgek looks good! Just missing a rebase/merge from `feat/v3` so we can merge it 🙂

2024-03-15 11:47 UTC, merged