[ENG-386] Change default favicon (and other Polkamarkets logo placeholders) to Foreland
Polkamarkets/polkamarkets-web pull request #511
Opened 2024-05-27 17:38 UTC by WellingtonMatheus

2024-05-27 20:58 UTC, danielgek approved these changes

2024-05-29 08:57 UTC, rsmarques requested changes

2024-05-29 08:57 UTC, rsmarques commented on src/components/Footer/Footer.tsx
> +        <ForelandIcon />
We're supposed to leave the Polkamarkets' logo on the footer @WellingtonMatheus. Can you revert this change please?

2024-05-29 17:09 UTC, rsmarques approved these changes

2024-05-29 17:10 UTC, merged